/* e-Vaarta Task & Work Operating System — Phases A–E. */
export const WORK_PHASE=Object.freeze({A:"execution",B:"workforce",C:"management",D:"evidence",E:"intelligence"});
export const TASK_STATE=Object.freeze(["inbox","planned","ready","offered","assigned","accepted","in-progress","waiting","blocked","review","approved","verified","done","cancelled","deferred","rejected","duplicate"]);
export const VIEW=Object.freeze(["my-work","team-command","project-command","list","kanban","calendar","timeline","gantt","dependency-map","workload","portfolio"]);
export const NEGOTIATION=Object.freeze(["offered","accepted","declined","clarification","counter-proposed","resource-requested"]);
const arr=v=>Array.isArray(v)?[...v]:[];const n=v=>Math.max(0,Number(v)||0);const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,Number(v)||0));const iso=()=>new Date().toISOString();const uid=p=>p+"-"+Date.now()+"-"+Math.random().toString(36).slice(2,8);
export function createWorkTask(i={}){if(!i.id||!i.title)throw new TypeError("task id/title required");return Object.freeze({...i,status:TASK_STATE.includes(i.status)?i.status:"inbox",priority:i.priority??"medium",type:i.type??"task",creatorId:i.creatorId??null,projectId:i.projectId??null,programId:i.programId??null,portfolioId:i.portfolioId??null,parentId:i.parentId??null,assigneeId:i.assigneeId??null,teamId:i.teamId??null,followers:arr(i.followers),labels:arr(i.labels),customFields:{...(i.customFields||{})},dependsOn:arr(i.dependsOn),dependents:arr(i.dependents),startAt:i.startAt??null,dueAt:i.dueAt??null,estimateMinutes:n(i.estimateMinutes),actualMinutes:n(i.actualMinutes),remainingMinutes:n(i.remainingMinutes??i.estimateMinutes),progress:clamp(i.progress,0,100),skills:arr(i.skills),resources:arr(i.resources),checklist:arr(i.checklist),evidenceIds:arr(i.evidenceIds),decisionIds:arr(i.decisionIds),sourceIds:arr(i.sourceIds),risks:arr(i.risks),approvals:arr(i.approvals),comments:arr(i.comments),attachments:arr(i.attachments),timeEntries:arr(i.timeEntries),recurrence:i.recurrence??null,sla:i.sla??null,baseline:i.baseline??null,activity:arr(i.activity),createdAt:i.createdAt??iso(),updatedAt:i.updatedAt??iso(),version:n(i.version)||1});}
export function assignWork(t,c={}){const a={id:uid("assignment"),mode:c.mode??"direct",assigneeId:c.assigneeId??null,teamId:c.teamId??null,role:c.role??null,rationale:c.rationale??null,score:n(c.score),alternatives:arr(c.alternatives),state:"offered",offeredAt:iso(),acceptedAt:null};return {...t,assigneeId:a.assigneeId,teamId:a.teamId,status:a.assigneeId||a.teamId?"offered":t.status,assignment:a,updatedAt:iso(),version:t.version+1};}
export function negotiateAssignment(t,state,details={}){if(!NEGOTIATION.includes(state))throw new RangeError("invalid assignment negotiation state");const e={id:uid("negotiation"),state,details,at:iso()};return {...t,assignment:{...(t.assignment||{}),state,negotiation:[...(t.assignment?.negotiation||[]),e]},status:state==="accepted"?"accepted":state==="declined"?"rejected":"offered",updatedAt:iso(),version:t.version+1};}
export function scoreAssignment(t,cs=[]){const need=new Set(arr(t.skills));return cs.map(c=>{const skills=new Set(arr(c.skills)),skill=need.size?[...need].filter(x=>skills.has(x)).length/need.size:1,cap=n(c.capacityMinutes),comm=n(c.committedMinutes),availability=cap?clamp((cap-comm)/cap):1,membership=!t.projectId||arr(c.projectIds).includes(t.projectId)?1:0,permission=c.authorized===false?0:1,timezone=c.timezoneCompatible===false?.5:1,score:.25*skill+.25*availability+.15*membership+.25*permission+.1*timezone;return {...c,score,explanation:{skill,availability,membership,permission,timezone}};}).filter(c=>c.authorized!==false).sort((a,b)=>b.score-a.score);}
export function recommendAssignment(t,cs=[]){const r=scoreAssignment(t,cs);return r[0]?{recommended:r[0],alternatives:r.slice(1,4)}:null;}
export function capacityPlan(ps=[],ts=[],calendar={}){return ps.map(p=>{const xs=ts.filter(t=>t.assigneeId===p.id&&!["done","verified","cancelled"].includes(t.status)),committed=xs.reduce((s,t)=>s+n(t.remainingMinutes||t.estimateMinutes),0),cap=n(p.capacityMinutes)||n(calendar.defaultCapacityMinutes),available=Math.max(0,cap-committed);return {...p,taskIds:xs.map(t=>t.id),capacityMinutes:cap,committedMinutes:committed,availableMinutes:available,utilization:cap?committed/cap:0,overloaded:committed>cap};});}
export function simulateCapacityChange(ts,ps,change){return capacityPlan(ps.map(p=>p.id===change.personId?{...p,capacityMinutes:n(change.capacityMinutes)}:p),ts);}
export function scheduleWork(t,{startAt=null,calendarMinutesPerDay=480,dependencyEndAt=null}={}){const effort=n(t.remainingMinutes||t.estimateMinutes),start=Math.max(startAt?Date.parse(startAt):Date.now(),dependencyEndAt?Date.parse(dependencyEndAt):0),days=Math.ceil(effort/Math.max(1,calendarMinutesPerDay));return {...t,scheduledStartAt:new Date(start).toISOString(),scheduledDueAt:new Date(start+days*86400000).toISOString()};}
export function dependencyImpact(ts,id){const seen=new Set(),q=[id],out=[];while(q.length){const x=q.shift();for(const t of ts)if(arr(t.dependsOn).includes(x)&&!seen.has(t.id)){seen.add(t.id);out.push(t.id);q.push(t.id);}}return {taskId:id,affectedTaskIds:out};}
export function criticalChain(ts=[]){const by=new Map(ts.map(t=>[t.id,t])),memo=new Map(),vis=new Set();const len=id=>{if(memo.has(id))return memo.get(id);if(vis.has(id))throw new Error("cyclic task graph");vis.add(id);const t=by.get(id),v=t?n(t.remainingMinutes||t.estimateMinutes)+Math.max(0,...arr(t.dependsOn).map(len)):0;vis.delete(id);memo.set(id,v);return v;};return ts.map(t=>({id:t.id,pathMinutes:len(t.id)})).sort((a,b)=>b.pathMinutes-a.pathMinutes);}
export function taskViews(ts=[],o={}){const f=o.filter?ts.filter(o.filter):ts;return {list:f,kanban:Object.fromEntries(TASK_STATE.map(s=>[s,f.filter(t=>t.status===s)])),calendar:f.filter(t=>t.startAt||t.dueAt),timeline:f.filter(t=>t.startAt||t.dueAt),gantt:f.map(t=>({id:t.id,start:t.startAt,end:t.dueAt,progress:t.progress,dependsOn:arr(t.dependsOn)})),myWork:f.filter(t=>t.assigneeId===o.userId),teamCommand:f.filter(t=>o.teamId?t.teamId===o.teamId:true),projectCommand:f.filter(t=>o.projectId?t.projectId===o.projectId:true),dependencyMap:f.map(t=>({id:t.id,dependsOn:arr(t.dependsOn)})),workload:o.people?capacityPlan(o.people,f):[]};}
export function createWipPolicy(i={}){return {id:i.id||uid("wip"),columns:{...(i.columns||{})},enforced:Boolean(i.enforced)};}export function validateWip(ts=[],p={}){return Object.entries(p.columns||{}).map(([status,limit])=>{const count=ts.filter(t=>t.status===status).length;return {status,count,limit,within:count<=limit};});}
export function recurringInstances(t,count=1){if(!t.recurrence||count<1)return [];return Array.from({length:count},(_,i)=>({...t,id:t.id+"#"+(i+1),parentRecurringId:t.id,status:"planned",createdAt:iso(),updatedAt:iso()}));}
export function promoteChecklistItem(t,id){const x=arr(t.checklist).find(v=>v.id===id||v.text===id);if(!x)throw new Error("checklist item not found");return createWorkTask({id:uid("task"),title:x.text||x.title||id,parentId:t.id,projectId:t.projectId,creatorId:t.creatorId,status:"planned"});}
export function logWork(t,e={}){const m=n(e.minutes);return {...t,timeEntries:[...arr(t.timeEntries),{...e,id:e.id||uid("time"),minutes:m,at:iso()}],actualMinutes:n(t.actualMinutes)+m,remainingMinutes:Math.max(0,n(t.remainingMinutes)-m),updatedAt:iso(),version:t.version+1};}
export function monitorWork(t,c={}){const now=c.now?Date.parse(c.now):Date.now(),due=t.dueAt?Date.parse(t.dueAt):null,last=t.updatedAt?Date.parse(t.updatedAt):now,stale=now-last>=n(c.staleAfterHours||72)*3600000,overdue=!!due&&now>due&&!["done","verified","cancelled"].includes(t.status),missingEvidence=t.status==="review"&&!arr(t.evidenceIds).length,approvalPending=t.status==="review"&&arr(t.approvals).some(a=>a.status==="pending"),health=t.status==="blocked"?"blocked":!t.assigneeId&&!t.teamId?"unassigned":t.assignment?.state==="offered"?"unaccepted":overdue?"late":stale?"stalled":missingEvidence||approvalPending?"at-risk":"on-track",causes=[];if(!t.assigneeId&&!t.teamId)causes.push("person");if(t.status==="blocked")causes.push("dependency");if(approvalPending)causes.push("approval");if(missingEvidence)causes.push("information");return {health,overdue,stalled:stale,missingEvidence,approvalPending,causes};}
export function taskHealthScore(t,c={}){const m=monitorWork(t,c);let s=100;if(m.overdue)s-=30;if(m.stalled)s-=20;if(m.health==="blocked")s-=25;if(m.health==="unassigned")s-=15;if(m.health==="unaccepted")s-=10;if(m.missingEvidence)s-=10;if(m.approvalPending)s-=10;return Math.max(0,Math.min(100,s));}
export function predictCompletion(t,ps=[],c={}){const r=n(t.remainingMinutes||t.estimateMinutes),p=ps.find(x=>x.id===t.assigneeId),daily=Math.max(1,n(p?.capacityMinutes||c.dailyCapacityMinutes||480)-n(p?.committedMinutes||0)),days=Math.ceil(r/daily);return {taskId:t.id,estimatedDays:days,estimatedCompletion:new Date(Date.now()+days*86400000).toISOString(),confidence:t.dependsOn?.length ? .65 : .8};}
export function optimizeSchedule(ts=[],ps=[],c={}){const proposals=[];for(const t of ts.filter(x=>x.status!=="done")){const r=scoreAssignment(t,ps);if(r[0]&&r[0].id!==t.assigneeId)proposals.push({taskId:t.id,action:"reassign",to:r[0].id,score:r[0].score});}return {proposals,capacity:capacityPlan(ps,ts),requiresAuthorization:true};}
export function createEscalationPolicy(i={}){return {id:i.id||uid("escalation"),stages:arr(i.stages),businessCalendar:i.businessCalendar??null,pauseStates:arr(i.pauseStates),audit:true};}export function evaluateEscalation(t,h,p){return arr(p?.stages).filter(s=>s.health===h||s.trigger===h).map(s=>({taskId:t.id,stage:s.stage||s.order,recipient:s.recipient,action:s.action,reason:h,at:iso()}));}
export function createSla(i={}){return {responseMinutes:n(i.responseMinutes),resolutionMinutes:n(i.resolutionMinutes),warningPercent:n(i.warningPercent||80),pauseStates:arr(i.pauseStates),businessCalendar:i.businessCalendar??null};}export function evaluateSla(t,sla,elapsedMinutes){if(!sla)return {status:"none"};const pct=sla.resolutionMinutes?elapsedMinutes/sla.resolutionMinutes*100:0;return {status:pct>=100?"breached":pct>=sla.warningPercent?"at-risk":"on-track",elapsedMinutes,pct};}
export function completeTask(t,{evidenceIds=[],approvalId=null,verified=false,reason=null}={}){const ids=[...new Set([...arr(t.evidenceIds),...evidenceIds])];return {...t,status:verified?"verified":ids.length?"review":"done",evidenceIds:ids,completion:{submittedAt:iso(),approvalId,verified,reason},updatedAt:iso(),version:t.version+1};}export function verifyTask(t,v={}){if(!arr(t.evidenceIds).length&&!v.allowWithoutEvidence)throw new Error("verification requires evidence");return {...t,status:"verified",verification:{...v,verifiedAt:iso()},updatedAt:iso(),version:t.version+1};}
export function decisionToTask(d,t={}){return createWorkTask({id:t.id||uid("task"),title:t.title||d.title||"Decision action",description:t.description||d.summary||"",projectId:t.projectId||null,decisionIds:[d.id],sourceIds:arr(d.sourceIds),evidenceIds:arr(d.evidenceIds),status:"planned",priority:t.priority||"high"});}export function evidenceToTask(e,t={}){return createWorkTask({id:t.id||uid("task"),title:t.title||"Evidence action",description:t.description||e.quote||"",projectId:t.projectId||null,evidenceIds:[e.id],sourceIds:arr(e.sourceIds),status:"planned"});}
export function traceTask(t,g={}){return {taskId:t.id,stages:["communication","document","evidence","claim","finding","decision","task","assignment","execution","verification","report","communication-output"],linked:{decision:arr(t.decisionIds),evidence:arr(t.evidenceIds),sources:arr(t.sourceIds),project:t.projectId},complete:Boolean(g.decision||t.decisionIds.length)&&t.evidenceIds.length>0};}
export function createRisk(i={}){const p=clamp(i.probability),x=clamp(i.impact);return {id:i.id||uid("risk"),title:i.title||"Risk",probability:p,impact:x,score:p*x,ownerId:i.ownerId??null,mitigation:i.mitigation??null,evidenceIds:arr(i.evidenceIds),status:i.status||"open"};}
export function projectCommandCenter(project,ts=[],risks=[],ps=[]){const hs=ts.map(taskHealthScore),overdue=ts.filter(t=>monitorWork(t).overdue).length;return {projectId:project.id,taskCount:ts.length,completed:ts.filter(t=>["done","verified"].includes(t.status)).length,overdue,blocked:ts.filter(t=>t.status==="blocked").length,averageHealth:hs.length?hs.reduce((a,b)=>a+b,0)/hs.length:100,risks,capacity:capacityPlan(ps,ts),health:overdue||ts.some(t=>t.status==="blocked")?"at-risk":"on-track"};}
export function portfolioHealth(ps=[]){return ps.map(p=>({...p,health:p.health||"unknown",score:n(p.score)}));}
export function groundedProjectAnswer(question,c={}){const citations=arr(c.facts).map(f=>({sourceId:f.sourceId,evidenceId:f.evidenceId,quote:f.quote})).filter(x=>x.sourceId&&x.evidenceId);return {question,answer:c.answer||"",citations,grounded:citations.length>0,actions:arr(c.actions).map(a=>({...a,requiresAuthorization:true}))};}
export function projectReview(project,ts=[],c={}){const health=projectCommandCenter(project,ts,c.risks||[],c.people||[]);return {projectId:project.id,period:c.period||null,completed:ts.filter(t=>["done","verified"].includes(t.status)).map(t=>t.id),overdue:ts.filter(t=>monitorWork(t).overdue).map(t=>t.id),blocked:ts.filter(t=>t.status==="blocked").map(t=>t.id),decisions:arr(c.decisions),risks:arr(c.risks),nextPriorities:ts.filter(t=>!["done","cancelled"].includes(t.status)).sort((a,b)=>taskHealthScore(a)-taskHealthScore(b)).slice(0,10).map(t=>t.id),health};}
export const taskWorkOperatingSystemContract=Object.freeze({phaseA:{myWork:true,taskWorkspace:true,kanban:true,list:true,calendar:true,gantt:true,timeline:true,dependencies:true,checklists:true,recurrence:true,timeTracking:true},phaseB:{assignmentScoring:true,negotiation:true,capacity:true,workload:true,scheduling:true,predictiveDeadlines:true,resourceManagement:true},phaseC:{teamCommandCenter:true,projectCommandCenter:true,portfolio:true,risk:true,escalation:true,sla:true,forecasting:true},phaseD:{decisionToTask:true,evidenceToTask:true,evidenceCompletion:true,verification:true,impactAnalysis:true,evidenceReporting:true},phaseE:{assignmentAI:true,scheduleOptimization:true,stalledReasoning:true,riskPrediction:true,groundedControl:true,weeklyReview:true,authorizationBoundary:true,offlineExecution:true}});
