/* MPL-2.0 */
export const INTEGRATION_SURFACE=Object.freeze({ui:["unified-inbox","conversation","person","meeting","evidence","task","project","report"],transports:["email","sms","rcs","matrix","telegram","whatsapp","slack","teams"],calendar:["caldav","exchange","google"],security:["credential-store","key-store","capability-auth","audit","retention","legal-hold","dlp"],validation:["unit","integration","real-data","adversarial","performance","accessibility","device-offline","interoperability","human-benchmark"]});
export const INTEGRATION_STATUS=Object.freeze({NOT_CONFIGURED:"not-configured",CONFIGURED:"configured",CONNECTED:"connected",DEGRADED:"degraded",DISABLED:"disabled"});
export function createIntegrationState({id,type,status=INTEGRATION_STATUS.NOT_CONFIGURED,capabilities=[],lastSync=null,error=null}={}){return Object.freeze({schema:"evaarta.integration-state.v1",id,type,status,capabilities:[...new Set(capabilities)],lastSync,error});}
export function createUiProjection({surface,entityType,entityId,sourceIds=[],actions=[]}={}){return Object.freeze({schema:"evaarta.ui-projection.v1",surface,entityType,entityId,sourceIds:[...new Set(sourceIds)],actions});}
export function createTransportBoundary({provider,channel,operations=[],requiresCredentials=true,offlineQueue=true}={}){return Object.freeze({schema:"evaarta.transport-boundary.v1",provider,channel,operations:[...new Set(operations)],requiresCredentials,offlineQueue,canonicalState:"local-semantic-store"});}
export function createCredentialReference({provider,accountId,scope=[],secretRef=null}={}){if(!provider||!accountId)throw new TypeError("provider and accountId are required");return Object.freeze({schema:"evaarta.credential-reference.v1",provider,accountId,scope:[...new Set(scope)],secretRef,secretMaterial:null});}
export function createCapabilityToken({subject,capability,resource,expiresAt,nonce}={}){return Object.freeze({schema:"evaarta.capability-token.v1",subject,capability,resource,expiresAt,nonce});}
export function authorizeAction({token,now=new Date().toISOString(),requiredCapability,resource}={}){const valid=token&&token.capability===requiredCapability&&token.resource===resource&&(!token.expiresAt||new Date(token.expiresAt)>new Date(now));return {allowed:Boolean(valid),reason:valid?"authorized":"capability-or-expiry-failed"};}
export function createRetentionDecision({messageId,policy,now=new Date().toISOString()}={}){if(policy?.legalHold)return {messageId,action:"retain",reason:"legal-hold"};if(policy?.retentionDays==null)return {messageId,action:"retain",reason:"no-retention-policy"};return {messageId,action:"evaluate-age",retentionDays:policy.retentionDays,asOf:now};}
export function createValidationCase({id,domain,preconditions=[],steps=[],expected=[],environment="source"}={}){return Object.freeze({schema:"evaarta.integration-validation.v1",id,domain,preconditions,steps,expected,environment});}
export function productionIntegrationContract(){return Object.freeze({schema:"evaarta.production-integration.v1",offlineFirst:true,providerNeutral:true,failClosed:true,credentialSecretsNeverInSemanticObjects:true,uiIsProjection:true,requiredSurfaces:["communication","documents","evidence","projects","meetings","reports"],requiredValidation:["desktop-build","android-build","ios-build","provider-integration","offline-transition","security","accessibility","performance","interoperability"]});}
