/* e-Vaarta Production Work Graph & UX Engine — Phase F. */
const arr=v=>Array.isArray(v)?[...v]:[];const num=v=>Math.max(0,Number(v)||0);const now=()=>new Date().toISOString();const active=t=>!["done","verified","cancelled"].includes(t.status);
export const PHASE_F=Object.freeze({EXECUTION:"execution",PLANNING:"planning",MANAGEMENT:"management",WORKFLOW:"workflow",COLLABORATION:"collaboration",OFFLINE:"offline",INTELLIGENCE:"intelligence"});
export const WORKFLOW_EVENT=Object.freeze(["task.created","task.updated","task.assigned","task.accepted","task.blocked","task.completed","task.verified","evidence.added","decision.created","approval.completed","deadline.approaching","sla.breached","risk.changed"]);
export const NOTIFICATION_CHANNEL=Object.freeze(["in-app","email","push","digest"]);
export function buildWorkGraph(tasks=[],projects=[],people=[]){const byId=new Map(tasks.map(t=>[t.id,t]));return {tasks:[...tasks],projects:[...projects],people:[...people],dependencies:tasks.flatMap(t=>arr(t.dependsOn).map(d=>({from:d,to:t.id}))),roots:tasks.filter(t=>!arr(t.dependsOn).length).map(t=>t.id),active:tasks.filter(active).map(t=>t.id),index:byId};}
export function myWork(tasks=[],userId){return tasks.filter(t=>t.assigneeId===userId||arr(t.followers).includes(userId)).sort((a,b)=>String(a.dueAt||"9999").localeCompare(String(b.dueAt||"9999")));}
export function kanban(tasks=[],columns={}){const out={};for(const [key,statuses] of Object.entries(columns))out[key]=tasks.filter(t=>statuses.includes(t.status));return out;}
export function listView(tasks=[],query={}){let x=[...tasks];if(query.status)x=x.filter(t=>t.status===query.status);if(query.assigneeId)x=x.filter(t=>t.assigneeId===query.assigneeId);if(query.projectId)x=x.filter(t=>t.projectId===query.projectId);if(query.label)x=x.filter(t=>arr(t.labels).includes(query.label));if(query.text){const q=String(query.text).toLowerCase();x=x.filter(t=>String(t.title+" "+(t.description||"")).toLowerCase().includes(q));}return x;}
export function calendarView(tasks=[],start,end){const a=Date.parse(start),b=Date.parse(end);return tasks.filter(t=>{const s=Date.parse(t.startAt||t.dueAt||"");const e=Date.parse(t.dueAt||t.startAt||"");return Number.isFinite(s)&&s<=b&&e>=a;}).map(t=>({id:t.id,title:t.title,start:t.startAt||t.dueAt,end:t.dueAt||t.startAt,type:"task",projectId:t.projectId}));}
export function ganttModel(tasks=[]){return tasks.map(t=>({id:t.id,title:t.title,start:t.startAt,end:t.dueAt,progress:t.progress||0,dependsOn:arr(t.dependsOn),critical:false,baseline:t.baseline||null,health:t.health||null,evidenceIds:arr(t.evidenceIds),decisionIds:arr(t.decisionIds)}));}
export function criticalPath(tasks=[]){const by=new Map(tasks.map(t=>[t.id,t])),memo=new Map(),vis=new Set();const len=id=>{if(memo.has(id))return memo.get(id);if(vis.has(id))throw new Error("cyclic dependency graph");vis.add(id);const t=by.get(id);const v=t?num(t.remainingMinutes||t.estimateMinutes)+Math.max(0,...arr(t.dependsOn).map(len)):0;vis.delete(id);memo.set(id,v);return v;};return tasks.map(t=>({id:t.id,lengthMinutes:len(t.id)})).sort((a,b)=>b.lengthMinutes-a.lengthMinutes);}
export function workloadMatrix(tasks=[],people=[]){return people.map(p=>{const mine=tasks.filter(t=>t.assigneeId===p.id&&active(t));const committed=mine.reduce((s,t)=>s+num(t.remainingMinutes||t.estimateMinutes),0),capacity=num(p.capacityMinutes),utilization=capacity?committed/capacity:0;return {personId:p.id,taskIds:mine.map(t=>t.id),capacityMinutes:capacity,committedMinutes:committed,availableMinutes:Math.max(0,capacity-committed),utilization,overloaded:committed>capacity};});}
export function assignmentRecommendation(task,people=[]){const skills=new Set(arr(task.skills));return people.filter(p=>p.authorized!==false).map(p=>{const skill=skills.size?[...skills].filter(s=>arr(p.skills).includes(s)).length/skills.size:1;const capacity=num(p.capacityMinutes);const load=num(p.committedMinutes);const availability=capacity?Math.max(0,(capacity-load)/capacity):1;const membership=!task.projectId||arr(p.projectIds).includes(task.projectId)?1:0;const score=.45*skill+.35*availability+.2*membership;return {personId:p.id,score,explanation:{skill,availability,membership}};}).sort((a,b)=>b.score-a.score);}
export function negotiateAssignment(task,proposal){return {...task,assignmentProposal:{...proposal,status:"pending",createdAt:now()},status:"offered",updatedAt:now()};}
export function schedulePlan(tasks=[],people=[],calendar={}){const capacity=workloadMatrix(tasks,people),by=new Map(tasks.map(t=>[t.id,t]));const ordered=[...tasks].sort((a,b)=>criticalPath([a])[0].lengthMinutes-criticalPath([b])[0].lengthMinutes);const proposals=[];for(const t of ordered.filter(active)){const deps=arr(t.dependsOn).map(id=>by.get(id)).filter(Boolean);const depEnd=deps.map(x=>Date.parse(x.dueAt||x.startAt||"")).filter(Number.isFinite).reduce((m,x)=>Math.max(m,x),0);const start=Math.max(Date.now(),depEnd||0);const minutes=num(t.remainingMinutes||t.estimateMinutes);const days=Math.max(1,Math.ceil(minutes/num(calendar.minutesPerDay||480)));proposals.push({taskId:t.id,startAt:new Date(start).toISOString(),dueAt:new Date(start+days*86400000).toISOString(),dependencyEnd:depEnd?new Date(depEnd).toISOString():null});}return {proposals,capacity,requiresAuthorization:true};}
export function simulateSchedule(tasks,people,changes=[]){let xs=tasks.map(t=>({...t}));for(const c of changes){if(c.type==="assign")xs=xs.map(t=>t.id===c.taskId?{...t,assigneeId:c.personId}:t);if(c.type==="capacity")people=people.map(p=>p.id===c.personId?{...p,capacityMinutes:c.capacityMinutes}:p);}return schedulePlan(xs,people);}
export function createPortfolio(items=[]){return {items:items.map(p=>({...p,health:p.health||"unknown",riskIds:arr(p.riskIds),projectIds:arr(p.projectIds)})),createdAt:now()};}
export function portfolioHealth(projects=[],risks=[]){const r=new Map(risks.map(x=>[x.id,x]));return projects.map(p=>{const rs=arr(p.riskIds).map(id=>r.get(id)).filter(Boolean);const overdue=num(p.overdueTasks);const health=rs.some(x=>x.status!=="closed"&&x.probability*x.impact>=.5)||overdue>0?"at-risk":p.health||"on-track";return {projectId:p.id,health,openRisks:rs.filter(x=>x.status!=="closed").length,overdueTasks:overdue};});}
export function projectCommandCenter(project,tasks=[],risks=[]){const mine=tasks.filter(t=>t.projectId===project.id),health=portfolioHealth([{...project,overdueTasks:mine.filter(t=>monitorTask(t).overdue).length} ],risks)[0];return {project,health,tasks:mine,criticalPath:criticalPath(mine),risks:risks.filter(r=>arr(r.projectIds).includes(project.id)),workload:workloadMatrix(mine,project.people||[]),gantt:ganttModel(mine)};}
export function monitorTask(t,clock=Date.now()){const due=Date.parse(t.dueAt||"");const overdue=Number.isFinite(due)&&clock>due&&active(t);const stalled=clock-Date.parse(t.updatedAt||now())>72*3600000;const missingEvidence=t.status==="review"&&!arr(t.evidenceIds).length;return {overdue,stalled,missingEvidence,blocked:t.status==="blocked",unassigned:!t.assigneeId&&!t.teamId,health:t.status==="blocked"?"blocked":overdue?"late":stalled?"stalled":missingEvidence?"at-risk":"on-track"};}
export function createRisk(input={}){return {id:input.id||"risk-"+Date.now(),title:input.title||"Risk",probability:Math.max(0,Math.min(1,num(input.probability))),impact:Math.max(0,Math.min(1,num(input.impact))),ownerId:input.ownerId||null,projectIds:arr(input.projectIds),evidenceIds:arr(input.evidenceIds),status:input.status||"open",mitigation:input.mitigation||null};}
export function evidenceCompletion(task,evidenceIds=[],verification={}){const ids=[...new Set([...arr(task.evidenceIds),...evidenceIds])];return {...task,evidenceIds:ids,status:verification.verified?"verified":"review",verification:{...verification,submittedAt:now()}};}
export function createWorkflow(input={}){return {id:input.id||"workflow-"+Date.now(),name:input.name||"Workflow",trigger:input.trigger||"task.created",conditions:arr(input.conditions),actions:arr(input.actions),enabled:input.enabled!==false,authorization:input.authorization||"required",audit:true};}
export function evaluateWorkflow(workflow,event,context={}){if(!workflow.enabled||workflow.trigger!==event.type)return {matched:false,actions:[]};const conditions=workflow.conditions.every(c=>c.field?String(context[c.field])===String(c.equals):true);return {matched:conditions,actions:conditions?arr(workflow.actions).map(a=>({...a,requiresAuthorization:a.requiresAuthorization!==false})):[]};}
export function createNotificationPreference(input={}){return {userId:input.userId,events:arr(input.events),channels:arr(input.channels.length?input.channels:["in-app"]),digest:input.digest||null,quietHours:input.quietHours||null};}
export function notificationPlan(event,prefs=[]){return prefs.filter(p=>arr(p.events).includes(event.type)).map(p=>({userId:p.userId,channels:arr(p.channels),event,delivery:p.digest?"digest":"immediate"}));}
export function offlineWorkEvent(input={}){return {eventId:input.eventId||"evt-"+Date.now()+Math.random(),deviceId:input.deviceId,entityId:input.entityId,entityType:input.entityType||"task",operation:input.operation,payload:input.payload||{},baseVersion:num(input.baseVersion),createdAt:input.createdAt||now(),idempotencyKey:input.idempotencyKey||input.eventId||null};}
export function reconcileWorkEvents(local=[],remote=[]){const seen=new Set(),merged=[];for(const e of [...local,...remote]){const key=e.idempotencyKey||e.eventId;if(seen.has(key))continue;seen.add(key);merged.push(e);}merged.sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)));return {events:merged,conflicts:merged.filter((e,i)=>i&&e.entityId===merged[i-1].entityId&&e.baseVersion===merged[i-1].baseVersion&&e.operation!==merged[i-1].operation)};}
export function groundedProjectControl(question,context={}){const q=String(question).toLowerCase();const answer=q.includes("block")?context.blockers||[]:q.includes("overload")?context.workload||[]:q.includes("risk")?context.risks||[]:q.includes("deadline")?context.atRisk||[]:context.summary||[];return {question,answer,sources:arr(context.sources),evidenceIds:arr(context.evidenceIds),grounded:true,authorizationRequired:q.includes("assign")||q.includes("change")};}
export function weeklyReview(project,tasks=[],events=[],risks=[]){const xs=tasks.filter(t=>t.projectId===project.id);return {projectId:project.id,completed:xs.filter(t=>t.status==="done"||t.status==="verified"),overdue:xs.filter(t=>monitorTask(t).overdue),blocked:xs.filter(t=>t.status==="blocked"),risks:risks.filter(r=>arr(r.projectIds).includes(project.id)&&r.status!=="closed"),decisions:events.filter(e=>e.type==="decision.created"),next:xs.filter(t=>["ready","assigned","accepted","in-progress"].includes(t.status)).slice(0,10),generatedAt:now()};}
export function createAutomation(input={}){return createWorkflow({...input,trigger:input.trigger||"task.updated"});}
export function taskWorkPhaseFContract(){return Object.freeze({phase:"F",capabilities:["work-graph","my-work","task-workspace","kanban","list","calendar","timeline","gantt","dependency-engine","critical-path","assignment-engine","negotiation","capacity","workload","scheduling","what-if","project-command-center","portfolio","risk","workflow-builder","notifications","evidence-verification","offline-events","conflict-review","grounded-project-control","weekly-review","authorization-boundary"]});}
