import { strict as assert } from "node:assert";
import { createWorkspaceCommand,isWorkspaceCommand } from "../../modules/EvaartaWorkspaceCommands.sys.mjs";
import { buildWorkspaceActivity } from "../../modules/EvaartaWorkspaceActivity.sys.mjs";
import { normalizeSearchState } from "../../modules/EvaartaSearchState.sys.mjs";
import { normalizeCaptureSelection,isDuplicateEvidence } from "../../modules/EvaartaEvidenceCapture.sys.mjs";
import { resolveAnchor } from "../../modules/EvaartaAnchorResolver.sys.mjs";
import { exportAnnotations,serializeAnnotations } from "../../modules/EvaartaAnnotationExport.sys.mjs";
import { diagnoseWorkspace } from "../../modules/EvaartaWorkspaceDiagnostics.sys.mjs";
import { validateWorkspaceTransfer } from "../../modules/EvaartaTransferValidator.sys.mjs";
import { createDeepLink,parseDeepLink } from "../../modules/EvaartaDeepLink.sys.mjs";
import { accessibleLabelForItem } from "../../modules/EvaartaAccessibility.sys.mjs";
const workspace={id:"ws-1",documents:[{id:"doc-1",title:"Policy",createdAt:"2026-01-01T00:00:00Z",updatedAt:"2026-01-02T00:00:00Z"}],items:[{id:"item-1",kind:"annotation",title:"Important",text:"hello",anchor:{documentId:"doc-1",page:2,startOffset:10,endOffset:15,quote:"hello"},annotation:{type:"highlight",color:"#ffdc00"},createdAt:"2026-01-01T00:00:00Z"}],links:[]};
const command=createWorkspaceCommand("search",{query:"policy"});assert.equal(isWorkspaceCommand(command),true);assert.equal(buildWorkspaceActivity(workspace).length,2);
assert.deepEqual(normalizeSearchState({query:" policy ",page:0}),{query:"policy",kind:"all",collectionId:null,documentId:null,page:1,limit:50});
const capture=normalizeCaptureSelection({documentId:"doc-1",text:" hello ",page:2,startOffset:10,endOffset:15});assert.equal(isDuplicateEvidence(workspace,capture),true);
assert.equal(resolveAnchor(workspace.documents[0],{documentId:"missing"}).status,"invalid");assert.equal(resolveAnchor(workspace.documents[0],{documentId:"doc-1",startOffset:10,endOffset:15}).status,"exact");
assert.equal(exportAnnotations(workspace).length,1);assert.match(serializeAnnotations(workspace),/annotations/);assert.equal(diagnoseWorkspace(workspace).healthy,true);
const transfer=JSON.stringify({persistenceVersion:1,workspaceId:"ws-1",revision:1,workspace});assert.equal(validateWorkspaceTransfer(transfer).valid,true);
const link=createDeepLink({workspaceId:"ws-1",documentId:"doc-1",itemId:"item-1"});assert.deepEqual(parseDeepLink(link),{workspaceId:"ws-1",documentId:"doc-1",itemId:"item-1"});assert.match(accessibleLabelForItem(workspace.items[0]),/annotation: Important, page 2/);
